apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kazoo
  labels:
    app: kazoo
    project: telephoneorg
    environment: production
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: kazoo
        project: telephoneorg
        environment: production
    spec:
      initContainers:
      - name: kubewait
        image: telephoneorg/kubewait
        imagePullPolicy: IfNotPresent
        args:
        - rabbitmq
        - couchdb
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
      - name: config
        image: telephoneorg/tmpld
        imagePullPolicy: IfNotPresent
        args:
        - tmpld /templates/*.j2
        env:
        - name: ERLANG_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: erlang.hostname
        - name: KUBE_HOSTNAME_FIX
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: kube.hostname.fix
        volumeMounts:
        - name: templates
          mountPath: /templates
        - name: config
          mountPath: /config
      containers:
      - name: kazoo
        image: telephoneorg/kazoo:latest
        imagePullPolicy: Always
        env:
        - name: ERLANG_HOSTNAME
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: erlang.hostname
        - name: KUBE_HOSTNAME_FIX
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: kube.hostname.fix
        - name: ERLANG_COOKIE
          valueFrom:
            secretKeyRef:
              name: erlang
              key: cookie
        - name: KAZOO_APPS
          valueFrom:
            configMapKeyRef:
              name: kazoo
              key: kazoo.apps
        ports:
        - name: crossbar
          containerPort: 8000
        - name: ws-tcp
          containerPort: 5555
        - name: ws-udp
          protocol: UDP
          containerPort: 5555
        - name: fax-smtp
          containerPort: 19025
        - name: media-proxy
          containerPort: 24517
        volumeMounts:
        - name: config
          mountPath: /config
        resources:
          requests:
            cpu: 3
            memory: 3Gi
          limits:
            cpu: 3
            memory: 3Gi
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 1200
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
      volumes:
      - name: templates
        configMap:
          name: kazoo-templates
      - name: config
        emptyDir: {}
      restartPolicy: Always
