apiVersion: v1
kind: ConfigMap
metadata:
  name: kazoo-templates
  labels:
    app: kazoo
    project: telephoneorg
    environment: production
data:
  sys.config.j2: |
    ---
    target: /config/sys.config
    ---
    
    {%- set config_map = env.get('CONFIG_MAP', 'kazoo') %}
    {% set config = kube.get('configmap', config_map).data -%}
    
    [
        {lager, [
            {handlers, [
                {lager_console_backend, info}
            ]},
        {colored, {{ config['kazoo.log.color'] }}},
        {colors, [
            {debug,     "\e[0;38m" },
            {info,      "\e[1;32m" },
            {notice,    "\e[1;36m" },
            {warning,   "\e[1;33m" },
            {error,     "\e[1;31m" },
            {critical,  "\e[1;35m" },
            {alert,     "\e[1;44m" },
            {emergency, "\e[1;41m" }
        ]},
        {error_logger_hwm, 500}
        ]}
    ].
  vm.args.j2: |
    ---
    target: /config/vm.args
    ---
    {% set config_map = env.get('CONFIG_MAP', 'kazoo') %}
    {% set config = kube.get('configmap', config_map).data -%}
    
    -sasl sasl_error_logger false
    
    -boot /opt/kazoo/releases/4.0.0/kazoo
    
    -mode interactive
    
    {% if config.get('erlang.hostname') == 'long' %}
    -name kazoo
    {% else %}
    -sname kazoo
    {% endif %}
    
    -config /config/sys.config
    
    -kernel inet_dist_listen_min 11500 inet_dist_listen_max 11999
    
    +K true
    
    +P {{ config.get('erlang.processes', shell('nproc') * 3200) }}
    
    +A {{ config.get('erlang.threads', shell('nproc') * 16) }}
    
    +W w
    
    +Bd -noinput
    
    -s kazoo_apps_app
  config.ini.j2: |
    ---
    target: /config/config.ini
    ---
    
    {%- set config_map = env.get('CONFIG_MAP', 'kazoo') %}
    {% set config = kube.get('configmap', config_map).data %}
    {% set rabbitmq = kube.get('secret', 'rabbitmq').data %}
    {% set erlang = kube.get('secret', 'erlang').data %}
    {% set couchdb = kube.get('secret', 'couchdb').data %}
    
    {% set zone = '{}-{}'.format(
        config.get('kazoo.country', 'us'), config.get('kazoo.region', 'east')
        ) %}
    {% set amqp_uri = 'amqp://{}:{}@{}:5672'.format(
        rabbitmq.get('user', 'guest'),
        rabbitmq.get('pass', 'guest'),
        config.get('rabbitmq.host', 'rabbitmq')
        ) %}
    {% set fqdn = shell('hostname -f') -%}
    
    [zone]
    name = {{ zone }}
    amqp_uri = "{{ amqp_uri }}"
    
    [bigcouch]
    ip = "{{ config.get('couchdb.host', 'couchdb-lb') }}"
    port = {{ config.get('couchdb.port', '5984') }}
    admin_port = {{ config.get('couchdb.admin-port', '5986') }}
    cookie = {{ erlang.get('cookie', 'insecure-cookie') }}
    compact_automatically = true
    {% if couchdb.get('user') and couchdb.get('pass') %}
    username = "{{ couchdb['user'] }}"
    password = "{{ couchdb['pass'] }}"
    {% endif %}
    
    [kazoo_apps]
    host = {{ fqdn }}
    cookie = {{ erlang.get('cookie', 'insecure-cookie') }}
    zone = {{ zone }}
    
    [log]
    console = {{ config.get('kazoo.log.level', 'info') }}
